### ISSUE TITLE
NTSG down

### ISSUE THREAD

**Issue by daliakopoulos** [MatMatt/MODIS#24]
Hello, thank you for the great contribution.

It seems source NTSG (ftp://ftp.ntsg.umt.edu) no longer works (turned into a web service?) so MOD16 can't be downloaded.

**Comment by daliakopoulos** [comment]
the solution is actually here: 
https://gis.stackexchange.com/questions/165084/how-to-download-mod16-modis-evapotranspiration-image

**Comment by fdetsch** [comment]
Great this solution has worked out fine. A lot of changes have been going on lately regarding the data structure and policy on both LP DAAC and NTSG. From the R side, this will all be fixed in an upcoming **MODIS** release which we hope will hit CRAN until this year's [useR!](https://user2017.brussels/).
