### ISSUE TITLE
Failure to download MOD44A or MOD44B -- Error in if (FtpDayDirs[1] == FALSE)

### ISSUE THREAD

**Issue by rsmiller74** [MatMatt/MODIS#33]
Looks like this is still unresolved?  I have updated MODIS as of Dec 19 and problem persists.  

> #-- Download and Mosaic Rasters
> sds <- runGdal( job="PercentTreeCover", product=product.type,
'+                 tileH=h.tiles, tileV=v.tiles,
'+                 begin=beg.date, end=end.date,
'+                 SDSstring=layers.vec, outProj=out.projection, overwrite=TRUE)
########################
outProj          =  +proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0 
pixelSize        =  asIn 
resamplingType   =  near 
Output Directory =  D:/MODIS//PercentTreeCover 
########################
Downloading structure on 'LPDAAC' for: MOD44A.004
Try: 1               
Error in if (FtpDayDirs[1] == FALSE) { : 
  missing value where TRUE/FALSE needed

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

**Comment by rsmiller74** [comment]
In addition I have tried both the CRAN version and also github version

devtools::install_github("MatMatt/MODIS", ref = "develop", force=TRUE)
require(MODIS)

**Comment by fdetsch** [comment]
Please mind that MOD44A was [discontinued after 2002](https://lpdaac.usgs.gov/dataset_discovery/modis/modis_products_table/mod44a), and the data directory on LP DAAC is actually empty. Simply follow this link to see for yourself: 

> $LPDAAC
> [1] "https://e4ftl01.cr.usgs.gov/MOLT/MOD44A.004

Due to the bare existence of this folder, `runGdal()` assumes that the corresponding tiles are still available online, but then collapses since it cannot find anything. I'll try to make the described error message a little more intuitive and, until the next CRAN release, remove the product from the list of MODLAND products available through **MODIS**.

As regards MOD44B, the product seems to be currently available from LP DAAC only. I'll remove LAADS from the list of supported servers for this product within the next couple of days. In the meantime, on my machine, something like

```
MODISoptions(MODISserverOrder = c("LPDAAC", "LAADS"))

sds <- runGdal(product = "MOD44B"
               , job = "PercentTreeCover"
               , SDSstring = "1000000"
               , tileH = 21, tileV = 9
               , begin = "2015.01.01"
               , outProj = "+init=epsg:4326")
sds
```

> $MOD44B.006
> $MOD44B.006$\`2015-03-06\`
> [1] "D:/Data/MODIS_\~1/PROCES\~1/PercentTreeCover/MOD44B.A2015065.Percent_Tree_Cover.tif"
> 
> $MOD44B.006$\`2016-03-05\`
> [1] "D:/Data/MODIS_\~1/PROCES\~1/PercentTreeCover/MOD44B.A2016065.Percent_Tree_Cover.tif"

runs absolutely smoothely, given that all the prerequisites for LP DAAC data download are met (see `?lpdaacLogin`). Since a couple of days have passed since you reported this, could you please reinstall **MODIS** from 'develop' (there have been quite some coding efforts lately) and give it another shot?

**Comment by fdetsch** [comment]
Done.

Since there are no files available from LP DAAC or LAADS, MOD44A has been removed from the **MODIS** list of products as of f45eabbbdc2cef5bca83fc055ea4f220dbcf4db6:

```
> jnk = getProduct("MOD44A")
No product found with the name MOD44A. Try 'getProduct()' to list available products.
```

Moreover, LAADS is no longer available as download server for MOD44B. Even if LAADS is your default server as defined through `MODISoptions(MODISserverOrder = ...)`, the single tiles will automatically be retrieved from LP DAAC given that Earthdata login credentials have been created eg. using `lpdaacLogin()`.

```
> MODIS:::genString("MOD44B")
$localPath
[1] "D:/Data/MODIS_~1/MODIS/MOD44B.006/DATE/"

$remotePath
$remotePath$LPDAAC
[1] "https://e4ftl01.cr.usgs.gov/MOLT/MOD44B.006/DATE"
```
