### ISSUE TITLE
runGdal subscript out of bounds error with v1.1.5

### ISSUE THREAD

**Issue by mstrimas** [MatMatt/MODIS#64]
The following code works fine in 1.1.4, but gives error `Error in product@CCC[[product@PRODUCT[z]]] : subscript out of bounds` in 1.1.5:

```
runGdal(product = "MCD12Q1.006", SDSstring = "01", 
        tileH = 10, tileV = 6,
        begin = "2017.01.01", end = "2017.12.31")
```

**Comment by fdetsch** [comment]
Thanks for reporting. From a backward compatibility perspective, this should definitely be reenabled in an upcoming release.

As a quick workaround, either specify the desired collection through the corresponding `runGdal()` argument:

```r
tfs1 = runGdal(product = "MCD12Q1", collection = "006", SDSstring = "01", 
              tileH = 10, tileV = 6,
              begin = "2016.01.01", end = "2016.12.31")
rst1 = raster(unlist(tfs1)) 
```

Or omit the collection entirely which seems justifiable since versions lower than V006 are no longer available from the main data servers.

```r
tfs2 = runGdal(product = "MCD12Q1", SDSstring = "01", 
              tileH = 10, tileV = 6,
              begin = "2017.01.01", end = "2017.12.31")
rst2 = raster(unlist(tfs2))
```

**Comment by mstrimas** [comment]
Thanks, that solved it!
