### ISSUE TITLE
Can anyone handle MCD19A2? Can you teach me?

### ISSUE THREAD

**Issue by Cattrees** [MatMatt/MODIS#68]
Can anyone handle MCD19A2? Can you teach me?

**Comment by fdetsch** [comment]
Please refer to my answer to [Download MODIS/MCD19A2 AOD product with R](https://gis.stackexchange.com/questions/295080/download-modis-mcd19a2-aod-product-with-r) on GIS StackExchange. If you feel more comfortable working with target extents from **sp**, **sf** or **raster** instead of full tiles, here's an example to get you going: 

```r
library(MODIS)

## define target extent
deu = getData(country = "Germany", level = 2, path = tmpDir())
ffm = subset(deu, NAME_2 == "Frankfurt am Main")

## get aerosol data
tfs = runGdal("MCD19A2"
              , begin = "2019001", end = "2019003"
              , extent = ffm
              , job = "mcd19a2_ffm", SDSstring = "1000000000000")

rst = stack(unlist(tfs))
```

Mind that in this case, the output inherits the CRS from the 'extent' object (EPSG:4326 in my case).
