### ISSUE TITLE
Problem with begin and end dates 

### ISSUE THREAD

**Issue by lsaravia** [MatMatt/MODIS#74]
I wanted to download and mosaic MOD44B, I selected one year, there is only one image in this range, but 2 images from different years were downloaded. 

```
runGdal("MOD44B",begin="2018001" ,end="2018365",tileH=9:14,tileV=7:14, SDSstring = "1")
########################
outProj          =  asIn 
pixelSize        =  asIn 
resamplingType   =  near 
Output directory =  /tmp/RtmpedgXlP/MODIS_ARC/PROCESSED/MOD44B.006_20190905183651  (no 'job' name specified, generated (date/time based))
########################
Local structure is up-to-date. Using offline information!
$MOD44B.006
$MOD44B.006$`2017-03-06`
[1] "/tmp/RtmpedgXlP/MODIS_ARC/PROCESSED/MOD44B.006_20190905183651/MOD44B.A2017065.Percent_Tree_Cover.tif"

$MOD44B.006$`2018-03-06`
[1] "/tmp/RtmpedgXlP/MODIS_ARC/PROCESSED/MOD44B.006_20190905183651/MOD44B.A2018065.Percent_Tree_Cover.tif"

```

Package versions are
` MODIS_1.1.5   raster_3.0-2  sp_1.3-1      mapdata_2.3.0 maps_3.3.0   
`

**Comment by fdetsch** [comment]
Good catch! As compared to all other annual products available through the package, this one actually starts with day of year 065 (March 5, see [here](https://lpdaac.usgs.gov/products/mod44bv006/)). 

For composite products like this one, `getHdf()` matches the user-defined start date (if provided) against the start of the composite periods. This is usually January 1 for annual products. If user and composite date do not line up, the preceding composite file is also downloaded to ensure that data is available for the full time range. This makes especially sense for 8-day or 16-day products where you usually cannot guess the start of a particular composite period during the year right away (see also #43 for clarification). 
Since you specified `"2018-01-01"`, but the composite period does not start before March 5, `getHdf()` included the 2017 file because it assumed the data wouldn't be complete otherwise. Does this make it somewhat more comprehensible? 

I figure that in the long run, this should be taken care of internally, which is why I'll leave this issue open for now. As a quick fix, you could simply adjust your start date: 

```r
tfs = runGdal("MOD44B", begin = "2018065" , end = "2018365"
              , tileH = 9:14, tileV = 7:14
              , SDSstring  =  "1", job = "test_mod44b")
tfs
# $MOD44B.006
# $MOD44B.006$`2018-03-06`
# [1] "~/Data/MODIS_ARC/PROCESSED/test_mod44b/MOD44B.A2018065.Percent_Tree_Cover.tif"
```

**Comment by fdetsch** [comment]
Decided against implementing this. As stated in the [MOD44B User Guide](https://lpdaac.usgs.gov/documents/112/MOD44B_User_Guide_V6.pdf), 

> The product date refers to the start date of the annual period so a product with ID “2005065” was produced with data from  2005065 – 2006064.

 A date range from `begin = "2018001", end = "2018365"` covers two such periods, thence the above described download behavior is intended.
