### ISSUE TITLE
PROJ6/GDAL3 causing "Cannot find proj.db" error

### ISSUE THREAD

**Issue by mstrimas** [MatMatt/MODIS#78]
I'm on Mac OS Mojave and recently updated to proj 6.2.1 and gdal 3.0.2 with homebrew, which resulted in the following error when calling `runGdal()`:

```
runGdal(product = "MCD12Q1", collection = "006", SDSstring = "01", 
        extent = "austria",
        begin = "2010.01.01", end = "2011.12.31", 
        outDirPath = "data", job = "modis",
        MODISserverOrder = "LPDAAC")
ERROR 1: PROJ: pj_obj_create: Cannot find proj.db
ERROR 1: PROJ: createGeodeticReferenceFrame: Cannot find proj.db
ERROR 1: PROJ: createGeodeticReferenceFrame: Cannot find proj.db
ERROR 1: PROJ: proj_as_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_as_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_wkt: Cannot find proj.db
ERROR 1: PROJ: pj_obj_create: Cannot find proj.db
ERROR 1: PROJ: createGeodeticReferenceFrame: Cannot find proj.db
ERROR 1: PROJ: createGeodeticReferenceFrame: Cannot find proj.db
ERROR 1: PROJ: proj_as_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_as_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_wkt: Cannot find proj.db
```

A little Googling turned up that it's looking for proj.gb in the `PROJ_LIB` environment variable, which is getting set to "/Users/mes335/Library/R/3.6/library/rgdal/proj" when MODIS is loaded. Through dumb luck I found that if I just nuke that env variable (`Sys.unsetenv("PROJ_LIB")`) everything works fine. No idea what's going on here, but would be nice to not have to always unset PROJ_LIB.

**Comment by mstrimas** [comment]
Update: I've just realized that, despite all the error messages, `runGDAL()` actually runs just fine and produces the correct output tifs. The error messages are extremely confusing though, so I think it would be worth looking into.

**Comment by fdetsch** [comment]
The issue is that PROJ_LIB is overridden as soon as **rgdal** or **sf** are attached. There is no file `proj.db` in the PROJ_LIB version shipped with these packages, and hence the error. I need to put some more thoughts in how we can handle this. In the meantime, `runGdal()` luckily just ignores the error.

**Comment by fdetsch** [comment]
@mstrimas Can you try again with the latest pkg version?

**Comment by mstrimas** [comment]
Can't even get to this point anymore, stuck in dependency hell. I have gdal installed with HDF4 support through brew, but still getting the `HDF4 driver seems to be lacking` error. Looking into `checkHdf4Driver()` I see it checks with `sf::st_drivers(what = "raster")$name`. Not clear what version of GDAL that's actually referencing, but it doesn't seem to be picking up the version of GDAL I installed with brew.

**Comment by fdetsch** [comment]
I believe it's referencing the GDAL version that ships with **sf**..

**Comment by mstrimas** [comment]
Hmm, I'm using the CRAN binary for sf, so I guess that doesn't include HDF4 support. Also, I assume none of the GDAL binaries ship with sf, just the libraries, so does it really make sense to use `sf::st_drivers(what = "raster")$name` to check for HDF4 support given that that isn't the version that will actually be used to convert the files?

**Comment by fdetsch** [comment]
I don't quite understand why this wouldn't be the version used to convert the files. Given that `sf::st_drivers(what = "raster")` does not report HDF4 support in your case, and drivers available depend on the installation of GDAL/OGR (see `?st_drivers`), wouldn't this indicate that **sf** isn't correctly linked to your local GDAL installation? Did you use `configure.args` during compilation as described [here](https://r-spatial.github.io/sf/#macos)?

**Comment by mstrimas** [comment]
I've never been able to get those sf install instructions to work for me, so I'm using the CRAN binaries for Mac OS. I suspect this will be the case with almost all sf users, except the few who have the knowledge and interest in compiling from source. So I don't think sf is linking to my system GDAL, e.g. when I load sf it says it's linking to GDAL 2.4.2, but my system GDAL is 2.4.4.

**Comment by tim-salabim** [comment]
@mstrimas have you tried installing sf from github? This may solve your issue in two ways.

a. If I am not mistaken, this will link to your system GDAL
b. IIRC, there have been efforts to ensure back-compatibility with older versions of GDAL/PROJ/GEOS (though that may already be included in the current CRAN version)

```r
remotes::install_github("r-spatial/sf")
```

All this is a major hick-up at the moment for many packages that rely on GDAL/PROJ/GEOS as those libs have gone through massive changes very rapidly lately.

**Comment by mstrimas** [comment]
Yeah, I have the latest versions of PROJ and GDAL installed via brew and have tried following the instructions for install from both CRAN and GitHub from source with no luck. Error is:

```
checking GDAL: checking whether PROJ is available for linking:... no
Undefined symbols for architecture x86_64:
  "OGRCreateCoordinateTransformation(OGRSpatialReference const*, OGRSpatialReference const*)", referenced from:
      _main in gdal_proj-20d5e8.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure: Install failure: compilation and/or linkage problems.
configure: error: cannot link projection code
ERROR: configuration failed for package ‘sf’
```

More broadly than my specific error, I think it should be expected that most people are using pre-compiled binaries of sf and will therefore not have the package linking to the system libraries.

**Comment by tim-salabim** [comment]
Well, then I think there's not much you can do but wait until MacOS binaries of sf ship with more recent versions of GDAL/PROJ/GEOS and hope that HDF4 driver is included then. 

This seems to me like it should be solved at the point where the MacOS binaries are built for CRAN. I don't know who is in charge of these but the windows binaries which are maintained by @jeroen (I think) include much more recent versions of GDAL/PROJ/GEOS and also the HDF4/5 drivers.

**Comment by mstrimas** [comment]
Ahh, looked at the source code, I see what's going on. I didn't realize MODIS was using `sf::gdal_utils(), I thought it was using the command line gdalwarp via system(). This makes sense now, but annoying since it means this package is unusable by the large majority of Mac OS users until those sf CRAN binaries get fixed.

**Comment by tim-salabim** [comment]
On the other hand, it takes burden off the maintainers. The problem is not with this package, the problem is with very old MacOs binaries. Maybe this should be raised on r-sig-mac

**Comment by fdetsch** [comment]
@mstrimas The pkg had been using `gdalinfo` and `gdalwarp` via `system()` calls before version 1.2.0. We would have had to check for the presence of GDAL utilities - and not install without them - if we had wanted to retain the pkg on CRAN in its old form. 

Now, quite a lot of users seemed to have problems with installing GDAL w/HDF4 support (Python bindings etc.) in the past, not to mention linking it to **MODIS**. At the same time, there is now a good number of pkgs out there that does a rather good job at this, making the whole process a lot more error prone and, as @tim-salabim mentions, less troublesome for us to maintain.   

So yeah, maybe r-sig-mac would be a good starting point to ensure a flawless experience for users on any OS.

**Comment by mstrimas** [comment]
Thanks both of you for explaining the thought process! Makes a lot of sense to use `sf::gdal_utils()` now that I understand. Seems like the thing to do is just to get those Mac OS binaries compiled with HDF4 support. I've posted to r-sig-mac, hopefully that gets the process started. Thanks!

**Comment by edzer** [comment]
You may want to try new Mac OSX binaries, kindly provided by Brian Ripley, see https://stat.ethz.ch/pipermail/r-sig-mac/2020-June/013599.html

I have no clue whether these include more drivers then the old OSX binaries. For OSX instructions for a source install of sf, see also https://github.com/r-spatial/sf/pull/1430

**Comment by mstrimas** [comment]
Thanks for the tip @edzer! Seems it doesn't include HDF4 support, but I've emailed Brian Ripley to see if it would be possible to add it.

**Comment by s-u** [comment]
MacOS CRAN binaries ship whatever the package maintainers deem appropriate so please contact them to submit whatever changes may be necessary to https://github.com/R-macos/recipes

**Comment by mstrimas** [comment]
No response from r-sig-geo or Brian Ripley. Seems like what @s-u suggested may be the way to go, but I'm totally at a loss for how to proceed with that. Perhaps one of the MODIS package maintainers could pursue that.

I think there should be some kind of warning for Mac users that MODIS won't work unless they compile `sf` from source linking to a version of GDAL with hdf4 support. The existing warning about hdf4 doesn't make it clear that it's an `sf` issue that can't be solved by adding hdf4 support to your system GDAL.

**Comment by tim-salabim** [comment]
I think this should be someone who has knowledge of macos. The only person coming to my mind is @pat-s. Not sure if he's aware of this process or would be able to contribute here. But it seems like it could resolve quite a few issues that have come up repeatedly in various places lately. Updating the macos gdal/proj/GEOS stack to recent stable versions would be great.

**Comment by mstrimas** [comment]
Thanks Tim! Wish I could be of more help here, but I'm totally lost when it comes to anything involving compiling, linking, etc.

**Comment by pat-s** [comment]
`hdf4` is somewhat niche I'd argue and the homebrew-core `gdal` formula does not come with `hdf4` support.
One reason maybe the lack of a `hdf4` formula in homebrew-core.

The `osgeo4mac` tap has a `osgeo-hdf4` formula. If this is installed and `osgeo-gdal` linked instead of `gdal`, then GDAL has `hdf4` support.

Not sure if `hdf4` support will ever make it into the CRAN binary.

I do not use binaries on macOS for exactly such issues. I want to be sure what is installed and what R packages link against and not guess (look up) what the binaries contain.

So in the end, what you want to do here to get this working (in case the lack of `hdf4` is the only issue):

```sh
brew install pkg-config # always good for linking
brew unlink gdal # in case its linked
brew tap osgeo/osgeo4mac
brew install osgeo-hdf4
brew install osgeo-gdal
brew link osgeo-gdal # might not be necessary
```

Then in R, (re-)install the spatial packages that rely on GDAL functionality from **source**

```r
install.packages(c("sf", "rgdal", "gdalUtils"))
```

**Comment by tim-salabim** [comment]
Thanks @pat-s ! @mstrimas can you try the install instructions from @pat-s and report back if this solves your missing hdf4 driver issue? If ti does, I think @fdetsch will add these instructions to the README to aid macos users with the same problem.

**Comment by s-u** [comment]
@tim-salabim the issue here is not specific to macOS and thus doesn't really require any macOS knowledge, but do you need to know what setup is required for your package. The only requirement relevant here is that your setup must work as a static build since it must be possible to compile the package in such a way that it doesn't depend on anything outside of your package when installed (this is used by the vast majority of users so not an unreasonable requirement). So, really, you jsut have to declare the flags you need in those libraries, that's all.

Unfortunately, to add to the problem, the libraries you rely on have bugs in recent versions that break when trying to build statically, so you either have to convince the maintainers to fix those or provide a work-around.

**Comment by mstrimas** [comment]
@tim-salabim As with the instructions in the `sf` README, the ones provided by @pat-s don't work unfortunately. I'm guessing this is the issue with static linking bugs that @s-u mentioned above. It's not clear to me if this is an issue specific to some oddity of my system or a general Mac OS problem. In any case, I have invested some time into trying to figure this out in the past, but have had no luck getting to the bottom of the problem.

**Comment by pat-s** [comment]
@mstrimas No worries talking to me directly :) 

To help you in more detail, we need more information -> a reprex and a more detailed error description using the `hdf4` enabled GDAL.
Are you sure you are having a static linking issue here? I am asking because you said earlier that you do not have much knowledge in linking and the instructions by Simon where very general and do not necessarily relate to your issue here.
Furthermore, if this would be true, the issue here would apply to all macOS users and be a way more general and probably cause failures for any spatial package in R (which I do not think).

Other than that, while trying this myself I am getting a false positive about GDAL not being installed at all from {MODIS} in https://github.com/MatMatt/MODIS/blob/012c3fa9960fdaa57d7abe70bb19ee0307ea800a/R/runGdal.R#L109-L111
which is a separate issue per se since I have a perfectly fine working (source) {rgdal}/GDAL installation.
I do not have time to look into this in more detail right now though.

**Comment by fdetsch** [comment]
@mstrimas Can you please provide the information that @pat-s is asking for? With our pkg now being built on `sf::gdal_utils()`, this is something that requires a sustainable solution.

@pat-s I'd be happy if you could move the latter part to a separate issue whenever it suits you. I might have a vague idea what could be going wrong..

**Comment by tim-salabim** [comment]
> Unfortunately, to add to the problem, the libraries you rely on have bugs in recent versions that break when trying to build statically, so you either have to convince the maintainers to fix those or provide a work-around.

@s-u which libraries are you referring to here?

**Comment by mstrimas** [comment]
@pat-s I suspect this will not be reproducible since it may depend on the particulars of my system. But here it goes. First, to be clear, this is an issue with compiling `sf` from source. I have no issue with using GDAL and HDF4 from the command line.

This is my session info:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.0.2
```

I ran the exact series of `brew` commands you provided above, then ran `install.packages("sf", type = "source")`, and go the following:

```
* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: clang
configure: CXX: clang++ -mmacosx-version-min=10.13 -std=gnu++11
checking for gdal-config... /Users/mes335/opt/anaconda3/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.4.4
checking GDAL version >= 2.0.1... yes
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /Users/mes335/opt/anaconda3/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... no
Undefined symbols for architecture x86_64:
  "OGRCreateCoordinateTransformation(OGRSpatialReference const*, OGRSpatialReference const*)", referenced from:
      _main in gdal_proj-14c205.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure: Install failure: compilation and/or linkage problems.
configure: error: cannot link projection code
ERROR: configuration failed for package ‘sf’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf’

The downloaded source packages are in
	‘/private/var/folders/_n/xby76_dj79j3nw_4pcmphbf40000gn/T/RtmpUdKUtY/downloaded_packages’
Warning message:
In install.packages("sf", type = "source") :
  installation of package ‘sf’ had non-zero exit status
```

I have also tried following the slightly different set of instructions on the `sf` [README](https://github.com/r-spatial/sf). The error is identical.

**Comment by edzer** [comment]
The test that fails tries to link against GDAL while calling PROJ code, checking that GDAL was linked against PROJ, so that the projection code in GDAL is usable (rgdal never does this check, as it doesn't use this code). Failure of this test can indicate a GDAL installation without PROJ (not so likely), a broken/mixed up GDAL installation, or a failure in the configure script. My guess is option 2, given that the script has worked well for many people, including OSX+brew users.

In your first comment here (Jan 9) you mention you have GDAL 3.0.2 installed; the configure script however indicates it finds GDAL 2.4.4. Do you have multiple versions installed? If so, that is a known recipe for disaster, mentioned on sf's README.

**Comment by mstrimas** [comment]
@edzer The instructions posted by Patrick above suggested using the osgeo version of GDAL vs. the standard version suggested in the README instructions, so I suspect those are the two version I have.

I'm not all that concerned with whether I can get this set working on my system, I mainly want to ensure it'll work for the average user since I rely heavily on the MODIS package workshops and [online resources for working with eBird data](https://cornelllabofornithology.github.io/ebird-best-practices/). From what Edzer is saying, it sounds like the "official" `sf` instructions should work for most Mac users, so perhaps making it clear in the MODIS README that users should following those instructions (with the additional step of `brew install hdf4` prior to `brew install gdal`) would be sufficient.

**Comment by s-u** [comment]
Please note that recommending homebrew for regular R is not a good idea as homebrew conflicts with system libraries and thus by induction with CRAN R which uses system libraries and not homebrew. If users want to use homebrew, they have to install everything via homebrew including R and all packages - and deal with the consequences, which I don't hink the majority want to.

If you have an R package that you want to make available to users, please use the official channel which allows you to setup any dependencies that are required for the package to function properly for all users so CRAN can distribute a binary that "just works" as usual on macOS. There are so many different issue with the geo-related libraries being discussed right now that it's hard to keep track who needs what exactly. At least clarifying that would help - all I got is that this thread had something to do with `hdf4` but also some newer version of the other libraries, but I see the requirement not documented anywhere. Main problem is that those fragile inter-dependencies seem to be utterly untested by the library authors so it requires manual intervention and I'm willing to look into it but need some detail on what the packages require.

**Comment by jeroen** [comment]
Simon, for the Windows stack I have used roughly the same versions as the latest Ubuntu 20.04 LTS. I found that these are well tested and also work with static linking. These are:

 - gdal 3.0.4
 - proj 6.3.1
 - geos 3.8.0

You can find the the full configuration, including the 26 driver libraries in the [PKGBUILD](https://github.com/r-windows/rtools-packages/blob/master/mingw-w64-gdal/PKGBUILD).

**Comment by tim-salabim** [comment]
@jeroen @s-u just as a thought, wouldn't it be desirable for R users in general to have the Windows and MacOS builds be as similar as possible so that we can expect things to work similarly independed of the OS used?

**Comment by edzer** [comment]
This discussion is very relevant, and is getting a scope way beyond the MODIS package. I suggest to continue it here: https://github.com/r-spatial/discuss/issues/40, and started bringing up a number of related things/thoughts and issues.

**Comment by tim-salabim** [comment]
Agreed!

**Comment by mstrimas** [comment]
Yes, this seems to be a much bigger discussion than what I originally raised. Closing this issue.

**Comment by pat-s** [comment]
> If users want to use homebrew, they have to install everything via homebrew including R and all packages - and deal with the consequences, which I don't hink the majority want to.

Simon, this statement is not true. I am running the official R CRAN binaries and use homebrew for everything. I did not have any conflicts yet and so have many others.
I do not use binaries and compile all packages from source.

Making such a strong statement and pulling users away from homebrew for no strong reasons is not a helpful move in my opinion, especially as your words have weight in the R community, especially for macOS.
I am sure many other macOS devs share my view here.
I know why you say this and what potential conflicts you are up to - but without more details, this can create more confusion than it helps.

@mstrimas 

I see that GDAL from anaconda is used: 

> checking GDAL: /Users/mes335/opt/anaconda3/share/gdal/pcs.csv readable... yes

I'd suspect the issues arise from there.
Anaconda causes problems in many cases related to R from my experience. I've seen so many issues related to anaconda jumping before everything else when it comes to local (system) paths and messing up system installations.
I cannot see what exactly is going on in your system, but sticking to plain homebrew and removing Anaconda completely would be my suggestion (which helped many times already in similar scenarios).
But this is just a suggestion, no guarantee that it will also work in your case ;)

**Comment by edzer** [comment]
> Simon, this statement is not true.

It's always nice to hear someone who not only has an opinion, but also knows the truth. I think Simon talked about users, not developers, and there's many more of the former group, and we (in any case Simon, Matt and I) need to deal with them.

Re: the GDAL version mix confusion: thanks for sifting this out, this was indeed what I suspected above. Are you willing to answer all the StackOverflow questions of this kind that will pop up after we recommend users to go the brew path?

**Comment by pat-s** [comment]
> It's always nice to hear someone who not only has an opinion, but also knows the truth. I think Simon talked about users, not developers, and there's many more of the former group, and we (in any case Simon, Matt and I) need to deal with them.

We all the need to deal with the users :) However, I do not see a difference between users and devs in the statement made: Recommending homebrew for "the average user" is just fine.
It is simple and when not going off-path, everything will run smoothly.
Also there is no need to install R via homebrew if homebrew is used in any way on the system.

> Re: the GDAL version mix confusion: thanks for sifting this out, this was indeed what I suspected above. Are you willing to answer all the StackOverflow questions of this kind that will pop up after we recommend users to go the brew path?

Spatial stack installations via homebrew for r-spatial packages were always "fine".
The recent issues where not related to homebrew packaging but GDAL and PROJ version incompatibilities (which arguably could also have been potentially be accounted for by the homebrew guys before upgrading one of the two).

I cannot/won't give a guarantee to answer all linking related (r-spatial) questions.
However, I've never ignored a ping in a comment so far...
I'm happy to share my opinion and experience of linking (spatial) R packages in source installations against their respective libs for several years now and how to do it in the least painful way.
However, often enough either my wording is problematic and/or pointing/commenting on rusty workflows is not the thing that gives the most karma points.

Due to exhausting discussions lately, my battery trying to change things to the better is very low right now.

**Comment by s-u** [comment]
@pat-s You don't have to take my word for it - you can check yourself `otool -L` is your friend. Saying that striking matches around hydrogen is perfectly safe just because you didn't blow yourself up yet is not a proof that it is actually true. In fact, it is simply irresponsible - there is already enough misinformation out there.

Homebrew replaces system libraries with its own versions which is safe as long as you don't mix it with binaries that are built with different tools and libraries. That's why the only safe way is to use Homebrew for everything since then you're guaranteed to have a consistent set of libraries and run-times, and that's what I said. I'm manning the ER so I see the people that blow themselves up.

The analogy is pretty accurate also because it is perfectly possible to handle hydrogen safely _if you know what you're doing_. I'm not advocating for users to avoid Homebrew on general principle. If you are aware of what you're doing it is perfectly fine to use it, but you have to know what you're doing since it is potentially dangerous to your system. I would claim that vast majority of people that will take the tutorial don't so that's precisely why I'm saying don't be irresponsible and spread dangerous rumours.

In all those decades that I manage Darwin binaries we have been through many package systems - Fink, MacPorts, Homebrew - of the lot Homebrew is arguably the best (Fink caused the most problems). It started with the very commendable idea that you should re-use system libraries and minimize conflicts. Unfortunately, after some time that requirement went out of the windows and Homebrew strayed from its course. The problems are inherent to the task - just as you pointed out all the Anaconda issues in the other post, they have the same root as it is the same approach.

So my point here is that there is no reason to instruct people to blow themselves up at all. We already have CRAN which is specifically designed to provide safe environment for users that don't need to know anything about the intricacies of their operating system. All it takes is to talk to CRAN (for macOS that's me) - it's better to solve the problem for all R MAc users than to have them create fragile ad-hoc environments that are affecting their entire system. I'm happy to discuss the details in a separate thread is you wish.

**Comment by mstrimas** [comment]
@pat-s thanks for catching that, I'd forgotten I had Anaconda installed. I have a new work MacBook on order, so I think I'm just going to wait for that and start fresh from a clean system.
